using System;
using AtividadePraticaCsharp;
//DiaDaSemana.Main(args);
//OperacoesAritmeticas.Main(args);
//ClassificacaoDeIdade.Main(args);
//MenuDeOpcoes.main(args);
//NotaDoAluno.main(args);
//EscolhaDeBebida.main(args);
//CalculadoraDeImpostos.main(args);
//ConversorDeTemperatura.main(args);
//CategoriaDeFilme.main(args);
//CalculadoraFatorial.main(args);